name: Build and Release

on: [push]

jobs:
  build_game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout repo to remote machine
      - name: Set up OpenJDK13 
        uses: actions/setup-java@v1
        with:
          java-version: '13'

      - name: Build Game
        run: |
          cd $GRADLE_DIR
          chmod +x ./gradlew
          ./gradlew --stacktrace build
        env:
          GRADLE_DIR: 'source' # Modify this to wherever './gradlew' is 
      - name: Tag release
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: 'latest'

      - name: Release Game
        uses: softprops/action-gh-release@v1
        with:
          files: desktop/build/libs/*.jar
          name: latest-release
          body: 'latest build'
          tag_name: 'latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          