name: Game Unit Tests

on: [push] # Will trigger whenever a push is made to the branch

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest # Running on this OS, if we need it changed lmk

    steps:
      - uses: actions/checkout@v2 # Checkout repo to remote machine
      - uses: nelonoel/branch-name@v1.0.1 # Here for simplicities sake for DECO people; lets us refer to branch as BRANCH_NAME
      - name: Set up OpenJDK13 
        uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: Build with Gradle
        id: test
        run: |
          $GRADLE_DIR/gradlew test
        env:
          GRADLE_DIR: './Source/'
      - name: Post to Slack # Notify the channel specified in the env variables
        if: ${{BRANCH_NAME}} == 'feat/github_workflow' # always run this step
        uses: rtCamp/action-slack-notify@v2.1.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEST }}
          SLACK_CHANNEL: 'bot-testing'
          SLACK_MESSAGE: 'Unit tests workflow reported *${{steps.test.conclusion}}*!'
          SLACK_COLOR: ${{job.status}} # Automatically changes color of the message
          SLACK_USERNAME: DECO2800 Overwatch
          SLACK_ICON: https://static.wikia.nocookie.net/1547a0b1-0227-43c5-ac81-9f1d0895824b